[package]
name = "FreeCoin"
version = "0.0.0"
upgrade_policy = "compatible"

[addresses]
# do not need to fill in an address
free_coin = "_"

[dependencies]
Faucet = { local = "../Faucet" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
