[package]
name = "Faucet"
version = "0.0.0"
upgrade_policy = "compatible"

[addresses]
# should fill in the correct address
faucet = "f8990f32707fe7a222f16780c350a638bf8372264dc9708f51ab4d513cef1124"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
